import React from 'react'

export default function Portfolio() {
  return (
    <div>
          <h1>Portfolio Page</h1>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatum temporibus accusamus illum. Deleniti quidem asperiores pariatur ratione, reprehenderit modi ducimus facilis inventore. Reprehenderit amet cum dolorem aut beatae maiores saepe, et rerum tempore eveniet dolorum ipsum aspernatur in quidem. Aut tempore quibusdam molestiae ipsam impedit. Quae corporis vitae illum doloribus veritatis necessitatibus totam, minus est deleniti. Omnis amet natus voluptate vitae deserunt beatae iusto! Pariatur odit velit adipisci error iure, necessitatibus saepe et corporis asperiores aperiam quas commodi aliquid? Sequi atque est, eius illo, pariatur nesciunt ullam obcaecati illum id vel, voluptatibus sunt nisi hic dolor perspiciatis itaque consequuntur quisquam eligendi fuga optio? Qui nesciunt laudantium soluta rerum recusandae excepturi veniam deleniti consequatur veritatis? Quia dolorem eaque placeat, error, itaque maiores recusandae similique nobis deserunt fugiat cumque amet reiciendis omnis quod delectus illum officia! Quaerat deserunt aliquid rerum sit officiis saepe temporibus aliquam dolore, ipsa ex autem officia nisi minima? Rerum voluptates quo, sed maiores excepturi accusamus. Ducimus, sunt quo cum at officia, dicta facere sed quaerat excepturi enim, accusamus perspiciatis nesciunt sapiente. Cumque sint id cum voluptatum accusantium a. Asperiores repudiandae consequatur, dignissimos reprehenderit, commodi modi facere nam vel necessitatibus quam tempora esse quis qui? Nostrum nihil rerum sed incidunt magnam corrupti suscipit temporibus deleniti enim debitis? Iste reprehenderit, possimus eaque ad, molestias libero est, facere fugiat qui aliquam sapiente. Delectus possimus explicabo repudiandae! Facere cupiditate corporis voluptate molestiae hic nihil quod a veniam quibusdam incidunt et reprehenderit velit ipsa temporibus iure at iusto, sit consectetur aperiam? Quo ad explicabo fugit veniam dolorem, reprehenderit repudiandae neque ullam nostrum eos. Quidem iure quo tempora ad suscipit ea earum officia, laboriosam, accusamus rem accusantium. Doloribus, quasi libero? Earum, aliquid animi atque voluptatem iste eaque porro beatae. Provident dolor architecto voluptatem nobis magni quasi natus fugit, temporibus eveniet praesentium mollitia expedita! Dolorum.</p>
    </div>
  )
}
