import React from 'react'

export default function Team() {
  return (
    <div>
      <h1>Team Page</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, voluptatibus corporis, fugiat excepturi commodi amet iusto quidem placeat libero quam nulla eius neque rerum ex sapiente quia nostrum deserunt qui. Numquam ipsam incidunt doloremque, itaque tempora repellat quo ducimus laudantium esse iusto quod sint inventore maxime tempore deserunt perferendis cum assumenda rerum quas at quos quam! Doloribus inventore alias minima, blanditiis odio corrupti et autem cupiditate soluta repellat sapiente nisi rerum consequuntur molestias provident dolores labore eos amet, ad placeat nihil, qui laboriosam enim. Delectus nihil similique nisi quis corporis? Molestiae omnis et in maiores animi, deserunt unde ad amet distinctio accusantium obcaecati fuga labore reiciendis adipisci vitae nulla dignissimos eligendi vel tenetur architecto. Quae magni quisquam deserunt aut libero ipsa aperiam quod iure atque nisi expedita numquam adipisci nesciunt quos voluptates doloribus, delectus eum minus ad commodi, voluptatum error alias praesentium. Unde, fugiat! Itaque, quaerat. Consequatur rerum nam mollitia quia reprehenderit veritatis culpa ullam voluptates, exercitationem sunt deleniti maxime commodi maiores, ratione nulla accusantium, consectetur veniam! Quas tenetur temporibus fuga consectetur maxime voluptatibus, doloremque aliquam officia reiciendis? Ipsam, laboriosam. Mollitia soluta at nam perferendis error esse aspernatur iusto qui cupiditate accusantium doloribus, nisi veniam vel eaque dolores amet natus incidunt, obcaecati rerum. Asperiores quos adipisci temporibus sequi, est sed dolorem explicabo illo laudantium, necessitatibus dolores voluptatibus. Vel blanditiis velit optio ea voluptatum eum? Quos aliquid mollitia dicta totam laborum, non esse et officia architecto expedita sunt nam adipisci necessitatibus omnis? Labore doloremque repellat consectetur numquam sunt dolore cupiditate vero dolorum eaque, perferendis totam. Praesentium architecto quam labore nemo itaque temporibus aspernatur illo hic minima vero fugit, molestiae deleniti sed maxime facere aliquid. Aperiam quo adipisci temporibus et qui repudiandae architecto cumque deserunt eaque quam nemo ducimus earum, eos, molestiae velit libero. Repellendus magnam repellat molestias minus. Blanditiis, eveniet voluptates.</p>
    </div>
  )
}
